#
# Spec file generated by kdist version v0.4-12-g6143
#
%define name		cpupower
%define version		3.3.0
%define src_uname_r	3.3.0-2
%define source_release	2
%define build_release	1%{nil}
%define archive		cpupower-3.3.0-2.1

%define build_srpm	1
%define no_source	1

%define _source_path	/usr/src/linux-%{src_uname_r}
%if %no_source
%define source_path	%{_source_path}/
%else
%define source_path	./
%endif

%define major		0
%define libname		%mklibname cpupower %{major}
%define devname		%mklibname cpupower -d

# Add "--without doc" option to disable documentation generation
%bcond_without doc

Name:			%{name}
Summary:		The power analysis tools for your processor
URL:			http://www.kernel.org
Group:			System/Kernel and hardware
License:		GPLv2
Version:		%{version}
Release:		%mkrel %{source_release}.%{build_release}
ExclusiveArch:		%{ix86} x86_64
%if %build_srpm
Source:			%{archive}.tar.bz2
%endif
BuildRoot:		%{_tmppath}/%{name}-%{version}-root
%if %no_source
BuildRequires:		kernel-source = %{version}-%{mkrel %{source_release}}
%endif
BuildRequires:		pciutils-devel
%ifarch %ix86
Buildrequires:		liblrmi0-devel
%endif
%description
cpupower is a collection of tools to examine and tune power saving
related features of your processor.

This collection of tools allow users and developers to have *one* tool
to get an overview what their system supports and to monitor and debug
CPU power management in detail.


%package -n %{libname}
Summary:		The shared library for %{name}
Group:			System/Kernel and hardware

%description -n %{libname}
"libcpupower" is a library which offers a unified access method for
userspace tools and programs to the cpufreq core and drivers in the
Linux kernel. This allows for code reduction in userspace tools, a
clean implementation of the interaction to the cpufreq core, and
support for both the sysfs and proc interfaces.


%package -n %{devname}
Summary:		The development files for %{name} shared library
Group:			System/Kernel and hardware
Requires:		%{libname} = %{version}-%{release}
Provides:		cpupower-devel = %{version}-%{release}

%description -n %{devname}
The development files needed for cpupower's shared library.

"libcpupower" is a library which offers a unified access method for
userspace tools and programs to the cpufreq core and drivers in the
Linux kernel. This allows for code reduction in userspace tools, a
clean implementation of the interaction to the cpufreq core, and
support for both the sysfs and proc interfaces.

%if %no_source
%define outdir_opt	O=$(pwd)
%endif

%global __cpupower_make	make %{?_smp_mflags} -C %{source_path}tools/power/%{name}
%global _cpupower_make	%{__cpupower_make} bindir=%{_bindir} libdir=%{_libdir} mandir=%{_mandir}
%global cpupower_make	%{_cpupower_make} %{?outdir_opt} DESTDIR=%{buildroot} CPUFREQ_BENCH=false

%if %build_srpm
%prep
%setup -q -n %{archive}
%endif
# when reusing the kernel source, the empty archive misses the
# README, so import it in that case.
test -f README || cp %{source_path}tools/power/%{name}/README .

# We're rebuilding in any cases (srpm or rpm) since the flags passed
# to make are not the same as the ones used by the user previously.
%build
%{cpupower_make}
%ifarch %ix86
%{cpupower_make} -C debug/i386
%endif
%ifarch x86_64
%{cpupower_make} -C debug/x86_64
%endif

%install
%{cpupower_make} install-lib install-tools
%if %{with doc}
%{cpupower_make} install-man
%endif
%ifarch %ix86
%{cpupower_make} -C debug/i386 install
%endif
%ifarch x86_64
%{cpupower_make} -C debug/x86_64 install
%endif

%clean
rm -rf %{buildroot}

%files
%defattr(-, root, root)
%{_bindir}/cpupower
%{_bindir}/centrino-decode
%{_bindir}/powernow-k8-decode
%if %{with doc}
%{_mandir}/man[1-8]/cpupower*
%endif
%ifarch %ix86
%{_bindir}/dump_psb
%{_bindir}/intel_gsic
%endif
%files -n %{libname}
%doc README
%{_libdir}/libcpupower.so.%{major}*

%files -n %{devname}
%doc README
%{_includedir}/cpufreq.h
%{_libdir}/libcpupower.so

%changelog
* Thu Mar 22 2012 Franck Bui <franck.bui@mandriva.com> 
  + Mandriva Release v3.3-2
  + drm/i915: enable RC6 by default on Sandy Bridge
